/* -*- mode: c++ -*-
 * Kaleidoscope-Python -- Wraps Kaleidoscope modules' c++
 *    code to be available in Python programs.
 * Copyright (C) 2017 noseglasses <shinynoseglasses@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "Kaleidoscope-Python.h"
#include "KeyboardReport.h"
#include "Kaleidoscope.h"
#include "Kaleidoscope-Hardware-Virtual.h"

#include "virtual_io.h"

#include <string.h>
#include <iostream>
#include <sstream>

namespace kaleidoscope {
 
// It the keymap can be properly parsed, this function is 
// replaced by a version generated by the build system based
// on the key names defined in the user sketch.
//
const char * __attribute__((weak)) 
   key_description(uint8_t /*layer*/, uint8_t /*row*/, uint8_t /*col*/)
{
   return nullptr;
}
   
namespace python {
   
class API
{
   public:
      
      static void init();
      static void finalize();
      
      static void scanCycle();
      
      static void tap(byte row, byte col);
      static void keyDown(byte row, byte col);
      static void keyUp(byte row, byte col);
      static bool isKeyPressed(byte row, byte col);
      static void clearAllKeys();
      
      static uint8_t matrixRows();
      static uint8_t matrixCols();
      
      static void setMillis(unsigned long millis);
      static unsigned long getMillis();
      
      static const char *getHardwareIDString();
      
      static void setKeyboardReportCallback(boost::python::object func);
      
   private:

      class KeyboardReportConsumer : public KeyboardReportConsumer_
      {
         public:
            
            friend class API;
            
            virtual void processKeyboardReport(
                           const HID_KeyboardReport_Data_t &reportData) override;
                           
         private:
            
            boost::python::object keyboardReportCallback_;
            
            KeyboardReport keyboardReport_;
      };
      
      static KeyboardReportConsumer keyboardReportConsumer_;
      
      static unsigned long millis_;
};

} // namespace python
} // namespace kaleidoscope

// Also defined by Kaleidoscope-Hardware-Virtual
//
void initVariant() __attribute__((weak));
void setup(void);

unsigned long millis(void) {
   return kaleidoscope::python::API::getMillis();
}

extern Virtual KeyboardHardware;

namespace kaleidoscope {
namespace python {

unsigned long API::millis_ = 0;
   
API::KeyboardReportConsumer API::keyboardReportConsumer_;

extern std::string getVersionString();
   
void 
   API
      ::init()
{
   KeyboardHardware.setEnableReadMatrix(false);
   
   Keyboard.setKeyboardReportConsumer(keyboardReportConsumer_);
   
	initVariant();

	setup();
}   

void 
   API
      ::finalize() {
   
   auto &finalizationCallbacks 
      = kaleidoscope::python::pluginFinalizationCallbacks();
   
   for(auto &cb: finalizationCallbacks) {
      cb();
   }
   
   keyboardReportConsumer_.keyboardReportCallback_ = boost::python::object();
}

void 
   API
      ::scanCycle()
{
   ::loop();
   nextCycle();
}

void  
   API
      ::tap(byte row, byte col)
{
   KeyboardHardware.setKeystate(row, col, Virtual::TAP);
}

void  
   API
      ::keyDown(byte row, byte col)
{
   KeyboardHardware.setKeystate(row, col, Virtual::PRESSED);
}

void  
   API
      ::keyUp(byte row, byte col)
{
   KeyboardHardware.setKeystate(row, col, Virtual::NOT_PRESSED);
}

bool 
   API
      ::isKeyPressed(byte row, byte col)
{
   return KeyboardHardware.getKeystate(row, col) == Virtual::PRESSED;
}

void  
   API
      ::clearAllKeys()
{
   for(byte row = 0; row < ROWS; row++) {
      for(byte col = 0; col < COLS; col++) {
         KeyboardHardware.setKeystate(row, col, Virtual::NOT_PRESSED);
      }
   }
}

uint8_t    
   API
      ::matrixRows() 
{ 
   return ROWS; 
}

uint8_t    
   API
      ::matrixCols()
{ 
   return COLS;
}

void   
   API
      ::setMillis(unsigned long millis)
{
   millis_ = millis;
}

unsigned long   
   API
      ::getMillis()
{
   return millis_;
}

const char *   
   API
      ::getHardwareIDString()
{
   return STRINGIZE(HARDWARE_IMPLEMENTATION);
}
      
void   
   API
      ::setKeyboardReportCallback(boost::python::object func)
{
   keyboardReportConsumer_.keyboardReportCallback_ = func;
}

void 
   API::KeyboardReportConsumer
      ::processKeyboardReport(
                           const HID_KeyboardReport_Data_t &reportData)
{
   this->keyboardReport_.setReportData(reportData);
   
   bool reportCallbackCalled = false;
   
   #define REPORT_CALLBACK_METHOD "processReport"
   
   if(this->keyboardReportCallback_) {
      
      boost::python::object processReport 
         = this->keyboardReportCallback_.attr(REPORT_CALLBACK_METHOD);
      
      if(processReport) {
         processReport(this->keyboardReport_);
         reportCallbackCalled = true;
      }
      else {
         std::cerr << "Error: Unable to find \"" REPORT_CALLBACK_METHOD "\" "
                        "method of callable python object" << std::endl;
      }
   }
   
   if(!reportCallbackCalled) {
      std::cerr << "Error: No report callback available" << std::endl;
      abort();
   }
}

// Generating KaleidoscopePluginRegistrationCallbacks as a static
// function scope variable avoids the "static initialization order fiasco".
//
PluginRegistrationCallbacks &pluginRegistrationCallbacks() {
   static PluginRegistrationCallbacks cb;
   return cb;
}

// Some plugins must make sure that their inventory is destroyed
// before the python interpreter is shut down.
//
PluginFinalizationCallbacks &pluginFinalizationCallbacks() {
   static PluginFinalizationCallbacks cb;
   return cb;
}

} // namespace python
} // namespace kaleidoscope

BOOST_PYTHON_MODULE(KALEIDOSCOPE_PYTHON_PACKAGE_NAME)
{
   // specify that this module is actually a package
   //
   boost::python::object package = boost::python::scope();
   package.attr("__path__") = STRINGIZE(KALEIDOSCOPE_PYTHON_PACKAGE_NAME);
   
   auto &registrationCallbacks 
      = kaleidoscope::python::pluginRegistrationCallbacks();
   
   for(auto &cb: registrationCallbacks) {
      cb();
   }
      
   #define EXPORT_STATIC_METHOD(NAME, DOCSTRING) \
      boost::python::def(#NAME, &kaleidoscope::python::API::NAME, DOCSTRING);
      
   EXPORT_STATIC_METHOD(
      init,
      "Initializes Kaleidoscope."
   )
   
   EXPORT_STATIC_METHOD(
      finalize,
      "Initializes Kaleidoscope."
   )


   EXPORT_STATIC_METHOD(
      scanCycle,
      "Performs a keyboard scan cycle."
   )
   
   EXPORT_STATIC_METHOD(
      tap,
      "Taps a key at a given position.\n\n"
      "Args:\n"
      "   row (int): The keymap row.\n"
      "   col (int): The keymap column.\n"
   )
   
   EXPORT_STATIC_METHOD(
      matrixRows,
      "Returns the number of matrix rows of the keyboard.\n\n"
      "Returns:\n"
      "   uint8_t: The number of matrix rows.\n"
   )
   
   EXPORT_STATIC_METHOD(
      matrixCols,
      "Returns the number of matrix cols of the keyboard.\n\n"
      "Returns:\n"
      "   uint8_t: The number of matrix cols.\n"
   )
   
   boost::python::def("millis", &millis, 
      "Returns the current state of the milliseconds timer.\n\n"
      "Returns:\n"
      "   long unsigned: The current state of the milliseconds timer."
   );
   
   EXPORT_STATIC_METHOD(
      getMillis,
      "Returns the current state of the milliseconds timer.\n\n"
      "Returns:\n"
      "   long unsigned: The current state of the milliseconds timer."
   )
   
   EXPORT_STATIC_METHOD(
      setMillis,
      "Sets the current state of the milliseconds timer.\n\n"
      "Args:\n"
      "   millis (long unsigned): The new state of the milliseconds timer."
   )
   
   EXPORT_STATIC_METHOD(
      setKeyboardReportCallback,
      "Allows to set a keyboard report callback.\n\n"
      "Args:\n"
      "   object (python object): A python class object that provides a "
      "processReport(keyboardReport) method that can be passed KeyboardReport class object"
   )
   
   EXPORT_STATIC_METHOD(
      getHardwareIDString,
      "Returns a string that identifies the hardware.\n\n"
      "Returns:\n"
      "   string: The hardware identification."
   )
   
   boost::python::def("getVersionString", &kaleidoscope::python::getVersionString,
      "Returns the current version of Kaleidoscope-Python.\n\n"
      "Returns:\n"
      "   string: The version string."
   )
   ;
   
   boost::python::def("getKeyDescription", &kaleidoscope::key_description,
      "Returns a string that describes the key at a given position on a layer.\n\n"
      "Args:\n"
      "   layer (uint8_t): The key layer.\n"
      "   row (uint8_t): The row where the key is located.\n"
      "   col (uint8_t): The column where the key is located.\n\n"
      "Returns:\n"
      "   string: The key description string."
   )
   ;
   
   // Cycles are handled on the python side
//    def("currentCycle", &currentCycle);
   
   #define EXPORT_STATIC_KEY_METHOD(NAME, DOCSTRING) \
      boost::python::def(#NAME, &kaleidoscope::python::API::NAME, DOCSTRING);
      EXPORT_STATIC_KEY_METHOD(
         keyDown,
         "Registeres a key being pressed at a given position.\n\n"
         "Args:\n"
         "   row (int): The keymap row.\n"
         "   col (int): The keymap column.\n"
      )
         
      EXPORT_STATIC_KEY_METHOD(
         keyUp,
         "Registeres a key being released at a given position.\n\n"
         "Args:\n"
         "   row (int): The keymap row.\n"
         "   col (int): The keymap column.\n"
      )
      
      EXPORT_STATIC_KEY_METHOD(
         isKeyPressed,
         "Checks it a key is pressed at a given position.\n\n"
         "Args:\n"
         "   row (int): The keymap row.\n"
         "   col (int): The keymap column.\n\n"
         "Returns:\n"
         "   bool: Wheter the key is currently pressed."
      )
      
      EXPORT_STATIC_KEY_METHOD(
         clearAllKeys,
         "Releases all keys that are currently pressed."
      )
}
